version: 2

jobs:

  build-python-library:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: Install Pre-Dependencies
          command: sudo pip install tox
      - restore_cache:
          key: v1-python-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: tox
      - save_cache:
          key: v1-python-dependencies-{{ checksum "setup.py" }}
          paths:
            - .tox
      - persist_to_workspace:
          root: ~/project
          paths:
            - vaultenv
            - setup.py
            - setup.cfg

  release-python-library:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate PyPi
          command: |
            echo "[distutils]" > ~/.pypirc
            echo "index-servers =" >> ~/.pypirc
            echo "    pypi" >> ~/.pypirc
            echo "" >> ~/.pypirc
            echo "[pypi]" >> ~/.pypirc
            echo "username:$PYPI_USERNAME" >> ~/.pypirc
            echo "password:$PYPI_PASSWORD" >> ~/.pypirc
            echo "" >> ~/.pypirc
      - run:
          name: Publish to PyPi
          command: python setup.py sdist upload -r pypi

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-python-library
      - release-python-library:
          requires:
            - build-python-library
          filters:
            branches:
              only: master
